---
version: '2'
services:
  ms-graph-kafka-connector:
    image: shop:1.08
    container_name: shop
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-XX:+UseSerialGC"
    volumes:
      - ./src/main/resources/application.yml:/application.yml