apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet: #check file on port
          path: /index.html
          port: 80
        initialDelaySeconds: 15 #initialy wait 15 seconds
        timeoutSeconds: 2 #timeout after 2 seconds
        periodSeconds: 5 #check every 5 seconds
        failureThreshold: 1 #allow 1 fail before failing pod