debug: true
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: /shop
      path-mapping:
        health: health